### ISSUE TITLE
error creating admin user

### ISSUE THREAD

**Issue by cmosetick** [fragmenta/fragmenta-cms#14] opened 2015-11-25 04:32 UTC
First pass after reorg to using `gb build all`

`./bin/server`

Using Postgres running on my local (Mac) system, from `brew install postgresql` (Highly possible it's not setup correctly.) It's v9.4.5 if that helps.

``` File:src/pages/actions/setup.go:53

Error:Error querying database for count: pq: relation "users" does not exist
Query:SELECT COUNT("id") FROM "users" WHERE (email=$1);
```

<img width="661" alt="screen shot 2015-11-24 at 8 25 43 pm" src="https://cloud.githubusercontent.com/assets/4873085/11388378/6042df78-92ea-11e5-924b-4d03638b4a3f.png">

**Comment by kennygrant** [comment] 2016-01-19 08:53
I think you haven't run the migrations on the database you're using. If you use psql and open the db, do you find the relation users?

I can't try to reproduce this as it is run against a modified version. Can you try it with a vanilla install, and make sure the db is populated with fragmenta migrate first?

**Comment by iHeeMo** [comment] 2016-03-20 09:36
I ran through this error, you have to create the database and restart the server

**Comment by kunafin** [comment] 2016-07-29 11:13
May be this userful:
You need to run "fragmenta migrate" from "postgres" user, because when you run it as ordinary user you can't create database (and tables) in Postgresql. Also, you can give access to Postgresql for standart system user.

**Comment by kennygrant** [comment] 2018-04-08 23:12
I think this is a dupe of #9 so closing, comment over there.

**Closed by kennygrant** 2018-04-08 23:12 UTC
